name: DokuWiki Default Tasks
on:
  push:
  pull_request:
  schedule:
    - cron: '25 3 21 * *'

permissions: write-all

jobs:
  all:
    uses: dokuwiki/github-action/.github/workflows/all.yml@composer
